Added the BMI header
NOAA-OWP/ngen pull request #193
Opened 2020-10-19 19:32 UTC by christophertubbs

I added the BMI header to the `include` directory, then added it to the .gitignore to prevent further modification.

As far as I understand, this is a reasonable way to do it? If not, I can play around with it some more.

2020-10-20 14:09 UTC, hellkite500 requested changes

2020-10-20 14:09 UTC, hellkite500 commented on include/bmi.hpp
> +
I would add the version of the BMI this corresponds to as either a macro or a comment (maybe both???) just to be clear.

2020-11-24 13:21 UTC, christophertubbs reviewed
Yeah, that makes perfect sense

2020-11-24 14:07 UTC, hellkite500 approved these changes

2020-11-24 14:07 UTC, merged