Inital Code for HY_Feature_MPI
NOAA-OWP/ngen pull request #275
Opened 2021-07-27 14:15 UTC by donaldwj

[Short description explaining the high-level reason for the pull request]

This is an inital implementation of the HY_Feature_MPI class.

## Additions

HY_Feature_MPI.hpp
HY_Feature_MPI .cpp

-

## Removals

-

## Changes

Added Hy_Features_MPI class for parallel runs.

-

## Testing

1.

## Screenshots

## Notes

-

## Todos

This is not necessarily considered complete yet

-

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [X] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [ ] Linux

2021-07-27 14:45 UTC, hellkite500 commented on src/NGen.cpp
> +        //arg 7 is the partion file path
what happened to arg 6?

2021-07-27 14:45 UTC, hellkite500 commented on src/NGen.cpp
> +          #endif
clean up indentation of macros

2021-07-27 14:45 UTC, hellkite500 commented on src/core/HY_Features_MPI.cpp
> +      std::unordered_map<std::string, HY_PointHydroNexusRemote::catcment_location_map_t> remote_connections;
Since this map has no external dependence, it should probably just be a member of PartitionData

2021-07-27 14:45 UTC, hellkite500 commented on test/utils/Partition_Test.cpp
> +    geojson::GeoJSON local_catchment_collection = geojson::read("/apd_common/test/hydrofabric/catchment_data.geojson", local_data.cat_ids);
still have a hard coded path here

2021-07-27 20:11 UTC, hellkite500 approved these changes

2021-07-27 21:31 UTC, robertbartel submitted a review, later dismissed

2021-07-27 21:33 UTC, robertbartel approved these changes

2021-07-27 21:36 UTC, robertbartel reviewed
Need to address output files.

2021-07-27 21:38 UTC, robertbartel requested changes
Need to go back and address output files.

2021-08-02 18:37 UTC, hellkite500 commented
All resulting changes from Demo 2 are included here.  I think we should investigate the output issues on a small test case before merging.  In looking at some random outputs from the HUC1 test, it looks like multiple writes were occurring in some nexus output files.

2021-08-02 18:43 UTC, donaldwj commented
We need to make sure the filtering of remote nexus is working correctly as the first step

2021-08-03 00:14 UTC, stcui007 commented
Does this happen for catchment output? If not, could it possibly have to do with multiple appearance of the same nexus id in a nexus list, both local and remote?

2021-08-03 15:48 UTC, donaldwj commented
The filtering is suppose to ensure that a nexus id is used for output on only one process. I suspect that there is a bug in the logic trying to enforce that condition

2021-08-16 18:26 UTC, robertbartel approved these changes
At this point, I think we need to go ahead and merge in these changes, and then separate continue working on troubleshooting the filtering/output issue.  I will wait a bit to proceed with that to give others some time to raise any objections.

2021-08-17 14:48 UTC, robertbartel commented
I opened #284 to track the issue with multiple writes separately, and will merge this in momentarily.

2021-08-17 14:49 UTC, merged