Passing catchment id to CatchmentAggrDataSelector
NOAA-OWP/ngen pull request #480
Opened 2022-11-23 16:05 UTC by stcui007

Passing catchment id in place of an empty string in get_value function.

## Additions

-

## Removals

-

## Changes

src/realizations/catchment/Simple_Lumped_Model_Realization.cpp
src/realizations/catchment/Tshirt_C_Realization.cpp
src/realizations/catchment/Tshirt_Realization.cpp

## Testing

1. Various Unit tests
2. Run ngen

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [x ] PR has an informative and human-readable title
- [x ] Changes are limited to a single goal (no scope creep)
- [x ] Code can be automatically merged (no conflicts)
- [x ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [x ] Linux

2022-12-09 21:21 UTC, mattw-nws requested changes

2022-12-09 21:21 UTC, mattw-nws commented on src/realizations/catchment/Simple_Lumped_Model_Realization.cpp
> +        precip = this->forcing->get_value(CatchmentAggrDataSelector(this->id, CSDMS_STD_NAME_LIQUID_EQ_PRECIP_RATE, t_current, t_delta_s, ""), data_access::SUM);
End result of this change is that the same thing is in the`try` and `catch` blocks. I think that the new DataProviders will reconcile these two different names so the try/catch is now unnecessary... remove the try/catch block and replace with just the one line.

2022-12-09 21:21 UTC, mattw-nws commented on src/realizations/catchment/Simple_Lumped_Model_Realization.cpp
> +    const std::string forcing_name = CSDMS_STD_NAME_LIQUID_EQ_PRECIP_RATE;
This is never used anywhere, please remove.

2022-12-09 22:23 UTC, stcui007 commented
Will do. Thanks.


On Fri, Dec 9, 2022 at 3:21 PM Matt Williamson ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/realizations/catchment/Simple_Lumped_Model_Realization.cpp
> <https://github.com/NOAA-OWP/ngen/pull/480#discussion_r1044846222>:
>
> >      try {
> -        precip = this->forcing->get_value(CatchmentAggrDataSelector("","precip_rate", t_unix, dt, "")); // classic forcing object/format
> +        precip = this->forcing->get_value(CatchmentAggrDataSelector(this->id, CSDMS_STD_NAME_LIQUID_EQ_PRECIP_RATE, t_current, t_delta_s, ""), data_access::SUM);
>
> End result of this change is that the same thing is in thetry and catch
> blocks. I think that the new DataProviders will reconcile these two
> different names so the try/catch is now unnecessary... remove the try/catch
> block and replace with just the one line.
> ------------------------------
>
> In src/realizations/catchment/Simple_Lumped_Model_Realization.cpp
> <https://github.com/NOAA-OWP/ngen/pull/480#discussion_r1044849766>:
>
> >      double precip;
> -    time_t t_unix = this->forcing->get_data_start_time() + (t * 3600);
> +    const std::string forcing_name = CSDMS_STD_NAME_LIQUID_EQ_PRECIP_RATE;
>
> This is never used anywhere, please remove.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-OWP/ngen/pull/480#pullrequestreview-1212261358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACA4SRNWB2BQMPMKSMRY64DWMOPGJANCNFSM6AAAAAASJEDA74>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-21 15:11 UTC, mattw-nws approved these changes

2022-12-21 15:11 UTC, merged