t-route (master branch) docs update
NOAA-OWP/ngen pull request #506
Opened 2023-03-29 17:56 UTC by mattw-nws

Documentation update to go with #502

## Additions

- Information specific to master branch, building and config differences *specific to ngen*

## Removals

- Old info relevant only to previous t-route (ngen branch) version
- References to using `extern/t-route`, which is no longer recommended

## Changes

- Removed some content and pointed back to t-route's page instead... this de-scoped documentation really needs to belong in the t-route repo and not in ngen, what is here is now largely specific to running t-route in/with ngen.

## Testing

1.

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows project standards (link if applicable)
- [X] Passes all existing automated tests
- [X] Any _change_ in functionality is tested
- [X] New functions are documented (with a description, list of inputs, and expected output)
- [X] Placeholder code is flagged / future todos are captured in comments
- [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [X] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [X] Linux

2023-05-31 19:25 UTC, aaraney requested changes
Thanks for adding this @mattw-nws! Ive added a few minor edits that im happy to contribute to your branch if you would like me to do that?

2023-05-31 20:21 UTC, mattw-nws commented on doc/PYTHON_ROUTING.md
> +```JSON
Neat... I have sometimes used `Javascript` instead but folks complained.

2023-05-31 20:29 UTC, mattw-nws commented on doc/PYTHON_ROUTING.md
> +## Installing t-route
Sure, that makes sense--I had just adapted the structure from the existing docs.

2023-05-31 20:33 UTC, mattw-nws commented on doc/PYTHON_ROUTING.md
> +```JSON
of course.... ngen's JSON parser doesn't support comments... yet... so that might lead to consternation for some.

2023-06-02 15:49 UTC, aaraney commented on doc/PYTHON_ROUTING.md
> +The t-route extension modules rely on netcdf fortran, and thus they need to be compiled with the same fortran compiler that compiled
I often bold **NOTE** at the beginning of the line, but that also not great. Im not aware of a more semantic way. I like you block quote approach though. The appearance is more like a text book or blog post.

2023-06-02 15:56 UTC, aaraney commented on doc/PYTHON_ROUTING.md
> +```JSON
Also my Friday is now instantly better having read the work _consternation_. Excellent word choice!

2023-06-02 16:09 UTC, aaraney commented
@mattw-nws, just made the changes to your branch. If you are happy with the changes, I think we are good to merge.

2023-06-05 18:32 UTC, aaraney approved these changes

2023-06-05 18:32 UTC, merged