Support numpy/python 32 bit float type names
NOAA-OWP/ngen pull request #800
Opened 2024-04-20 22:11 UTC by hellkite500

Add support for numpy/python 32 bit float type names in python bmi adapter.

## Changes

- python adapter now maps `float32`, `np.float32`, and `numpy.float32` to the cxx `float` type

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Linux
- [x] MacOs

2024-04-21 18:19 UTC, robertbartel requested changes
I had to go look it up, but apparently numpy's single-precision float type goes by the name `numpy.single` as well.  I suggested a change to account for this too.

Regardless, should we also update the _Variable Types and Sizes_ section of _doc/BMIconventions.md_?

2024-04-21 18:19 UTC, robertbartel commented on include/bmi/Bmi_Py_Adapter.hpp
> +                           py_type_name == "numpy.float32") && item_size == sizeof(float)) {
We might need to account for this as [`numpy.single`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.single) as well: 

```suggestion
                           py_type_name == "numpy.float32" || py_type_name == "np.single" ||  py_type_name == "numpy.single") && item_size == sizeof(float)) {
```

2024-04-22 13:22 UTC, hellkite500 commented
Updated bmi docs in 1d22bbcca4f3264f491f00580b09851df4eeaa41

2024-04-22 13:55 UTC, robertbartel approved these changes

2024-04-22 13:58 UTC, merged

2024-04-22 17:51 UTC, PhilMiller commented on doc/BMIconventions.md
>      * `int`, `long`, `long long`, `int64`, `longlong`, `float`, `float64`, `long double`
This missed documenting that `float32` is accepted

2024-04-22 17:51 UTC, PhilMiller commented on doc/BMIconventions.md
>      * `int`, `long`, `long long`, `int64`, `longlong`, `float`, `float64`, `long double`
(without a `numpy.` or `np.` prefix)